ARG IMGREPO

## Base Target

FROM ${IMGREPO}node:24-alpine AS base

RUN apk --no-cache add tzdata

ENV PORT=8000

ARG DL_HOST
ARG DL_PORT
ARG DL_PATH
ENV LOWDEFY_SECRET_DL_API=http://$DL_HOST:$DL_PORT$DL_PATH

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s CMD wget --no-verbose --tries=1 --spider http://localhost:8000 || exit 1

## Development Target:

FROM base AS develop

ARG VERSION

RUN corepack enable

WORKDIR /lowdefy

RUN chown node:node /lowdefy

USER node

RUN pnpm install lowdefy@${VERSION} @lowdefy/server-dev@${VERSION} \
 && cd node_modules/@lowdefy/server-dev \
 && pnpm install

RUN mkdir -p .lowdefy/dev \
 && cp -R node_modules/@lowdefy/server-dev/* .lowdefy/dev \
 && rm .lowdefy/dev/pnpm-lock.yaml

COPY assets/dataasee.svg         public/icon.svg
COPY assets/dataasee-32x32.png   public/icon-32.png
COPY assets/dataasee-512x512.png public/icon-512.png
COPY assets/dataasee-180x180.png public/apple-touch-icon.png
COPY assets/dataasee-250x72.png  public/logo-light-theme.png
COPY assets/dataasee-125x125.png public/logo-square-light-theme.png

COPY assets/colors.less public/styles.less

COPY frontend/sitemap.xml public/sitemap.xml

RUN ln -s /yaml/lowdefy.yaml lowdefy.yaml \
 && ln -s /yaml/templates templates \
 && ln -s /yaml/pages pages

CMD ["pnpm", "exec", "lowdefy", "dev", "--watch", "/yaml"]

## Build Target:

FROM develop AS build

ENV LOWDEFY_BUILD_OUTPUT_STANDALONE=1

RUN --mount=type=bind,source=./frontend,target=/yaml pnpm exec lowdefy build

## Release Target:

FROM base AS release

ARG DL_VERSION

LABEL org.opencontainers.image.title="DatAasee: Frontend"

LABEL org.opencontainers.image.version="${DL_VERSION}"

LABEL org.opencontainers.image.licenses="MIT"

LABEL org.opencontainers.image.url="https://github.com/ulbmuenster/dataasee"

LABEL org.opencontainers.image.authors="Christian Himpe (University of Münster)"

LABEL org.opencontainers.image.ref.name="dataasee"

USER root

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 lowdefy

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /lowdefy

COPY --from=build --chown=lowdefy:nodejs /lowdefy/.lowdefy/server/public ./public
COPY --from=build --chown=lowdefy:nodejs /lowdefy/.lowdefy/server/.next/standalone ./
COPY --from=build --chown=lowdefy:nodejs /lowdefy/.lowdefy/server/.next/static ./.next/static

USER lowdefy

ENV HOSTNAME=0::

CMD ["node","server.js"]
