ARG IMGREPO

## Development Target

FROM ${IMGREPO}ubuntu:24.04 AS develop

RUN apt-get update \
 && apt-get -y --no-install-recommends install tzdata wget openjdk-21-jre-headless \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -m arcadedb

RUN mkdir /backup && chown arcadedb:arcadedb /backup

WORKDIR /home/arcadedb

USER arcadedb

VOLUME /backup

ARG VERSION

# Only for testing an development snapshot:
#ARG TEST=25.4.1
#RUN wget -q -O arcadedb-$TEST.tar.gz https://s01.oss.sonatype.org/content/repositories/snapshots/com/arcadedb/arcadedb-package/$TEST-SNAPSHOT/arcadedb-package-$TEST-20250411.093019-45.tar.gz \
# && tar -xf arcadedb-$TEST.tar.gz \
# && mv arcadedb-*/* .

RUN wget -q https://github.com/ArcadeData/arcadedb/releases/download/$VERSION/arcadedb-$VERSION.tar.gz \
 && tar -xf arcadedb-$VERSION.tar.gz \
 && rm arcadedb-$VERSION.tar.gz \
 && mv arcadedb-$VERSION/* . \
 && rm -Rf arcadedb-$VERSION \
 && rm lib/js-language-*.jar \
 && rm bin/*.bat

ARG DB_NAME
ENV DB_NAME=$DB_NAME

COPY --chown=arcadedb database/init.sh ./

RUN --mount=type=bind,source=database/schema.sql,target=schema.sql \
    --mount=type=bind,source=database/preload.sql,target=preload.sql \
    --mount=type=bind,source=database/preload,target=preload \
    ./bin/console.sh -Darcadedb.dateFormat="yyyy-MM-dd HH:mm:ss" -b "CREATE DATABASE $DB_NAME; LOAD schema.sql; LOAD preload.sql;"

ENV ARCADEDB_PID="/tmp/arcadedb.pid"

ENV ARCADEDB_OPTS_MEMORY="-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"

ENV JAVA_OPTS="$JAVA_OPTS -Darcadedb.server.backupDirectory=/backup -Darcadedb.command.warningsEvery=10000"

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s CMD wget --no-verbose --tries=1 http://localhost:2480/api/v1/ready || exit 1

CMD ["./init.sh"]


## Release Target:

FROM develop AS release

ARG DL_VERSION

LABEL org.opencontainers.image.title="DatAasee: Database"

LABEL org.opencontainers.image.version="${DL_VERSION}"

LABEL org.opencontainers.image.licenses="MIT"

LABEL org.opencontainers.image.url="https://github.com/ulbmuenster/dataasee"

LABEL org.opencontainers.image.authors="Christian Himpe (University of Münster)"

LABEL org.opencontainers.image.ref.name="dataasee"

ENV JAVA_OPTS="$JAVA_OPTS -Darcadedb.server.mode=production"
