# DatAasee Github Pages Configuration

title: DatAasee - A Metadatalake for Libraries
description: DatAasee centralizes and interlinks distributed library/research metadata into an API‑first union catalog.
include:
  - README.md
  - CONTRIBUTORS.md
  - LICENSE
  - docs/docs.md
  - docs/arc42.md
  - docs/deps.md
  - docs/schema.md
theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
