# DatAasee 0.9
# ============
#
# Infos: https://github.com/ulbmuenster/dataasee
#
# Setup:
#  0. Move this compose file ("compose.yaml") to a dedicated directory
#  1. Make (or mount) a directory named "backup" with write permissions for root
#  2. Run: $  DL_PASS=password1 DB_PASS=password2 docker compose up -d

name: "dataasee"

networks:
  persistence:
  application:

secrets:
  database:
    environment: "DB_PASS"
  datalake:
    environment: "DL_PASS"

volumes:
  backup:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DL_BACKUP-./backup}"

services:

## Database ####################################################################

  database:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: "4G"
        reservations:
          cpus: "2.0"
          memory: "2G"
    environment:
      TZ: "${TZ-Europe/Berlin}"
      DB_PASS: "/db/secret"
    expose:
      - "2480"
    image: "harbor.uni-muenster.de/dataasee/database:${DL_VERSION-0.9}"
    init: true
    networks:
      - "persistence"
    restart: "unless-stopped"
    secrets:
      - source: "database"
        target: "/db/secret"
        mode: "444"
    stop_grace_period: "200s"
    volumes:
      - "backup:/backup"

## Backend #####################################################################

  backend:
    depends_on:
      - "database"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
        reservations:
          cpus: "1.0"
          memory: "1G"
    environment:
      TZ: "${TZ-Europe/Berlin}"
      DL_BASE: "http://${DL_BASE-localhost}:${DL_PORT-8343}"
      DL_USER: "${DL_USER-admin}"
      DL_PASS: "/dl/secret"
      DB_PASS: "/db/secret"
      DL_SAFE: "${DL_SAFE-false}"
    expose:
      - "4195"
    image: "harbor.uni-muenster.de/dataasee/backend:${DL_VERSION-0.9}"
    init: true
    networks:
      - "persistence"
      - "application"
    ports:
      - "0.0.0.0:${DL_PORT-8343}:8343"
    restart: "unless-stopped"
    secrets:
      - source: "database"
        target: "/db/secret"
        mode: "444"
      - source: "datalake"
        target: "/dl/secret"
        mode: "444"

## Frontend ####################################################################

  frontend:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
        reservations:
          cpus: "1.0"
          memory: "1G"
    environment:
      TZ: "${TZ-Europe/Berlin}"
    image: "harbor.uni-muenster.de/dataasee/frontend:${DL_VERSION-0.9}"
    init: true
    networks:
      - "application"
    ports:
      - "0.0.0.0:${FE_PORT-8000}:8000"
    restart: "unless-stopped"
