# Language: Compose YAML, Project: DatAasee, License: MIT, Author: Christian Himpe

name: "dataasee"

services:

## Database ####################################################################

  "database":
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        IMGREPO: "${ORIGIN:-}"
        VERSION: "$DB_VERSION"
        DB_NAME: "$DB_NAME"
        DL_VERSION: "$DL_VERSION"
      context: "."
      dockerfile: "container/Dockerfile.db"
      no_cache: true
      tags:
        - "$REGISTRY/$DL_REPO/database:$DL_VERSION"
      target: "release"
    image: "$REGISTRY/$DL_REPO/database:$DL_VERSION"

## Backend #####################################################################

  "backend":
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        IMGREPO: "${ORIGIN:-}"
        VERSION: "$BE_VERSION"
        DL_NAME: "$DL_NAME"
        DL_VERSION: "$DL_VERSION"
        DL_PORT: "8343"
        DL_PATH: "$DL_PATH"
        DB_HOST: "database"
        DB_PORT: "2480"
        DB_NAME: "$DB_NAME"
      context: "."
      dockerfile: "container/Dockerfile.be"
      no_cache: true
      tags:
        - "$REGISTRY/$DL_REPO/backend:$DL_VERSION"
      target: "release"
    depends_on:
      - "database"
    image: "$REGISTRY/$DL_REPO/backend:$DL_VERSION"

## Frontend ####################################################################

  "frontend":
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        IMGREPO: "${ORIGIN:-}"
        VERSION: "$FE_VERSION"
        DL_HOST: "backend"
        DL_PORT: "8343"
        DL_PATH: "$DL_PATH"
        DL_VERSION: "$DL_VERSION"
      context: "."
      dockerfile: "container/Dockerfile.fe"
      no_cache: true
      tags:
        - "$REGISTRY/$DL_REPO/frontend:$DL_VERSION"
      target: "release"
    image: "$REGISTRY/$DL_REPO/frontend:$DL_VERSION"
