-- Language: ArcadeDB SQL, Project: DatAasee, License: MIT, Author: Christian Himpe

-- Enumerated Properties

INSERT INTO BUCKET:categories (name) VALUES ('Protestant Theology'), ('Catholic Theology'), ('Law'), ('Business and Economics'), ('Medicine'), ('Educational Science'), ('Social Sciences'), ('Psychology'), ('Sport and Exercise Sciences'), ('History'), ('Philosophy'), ('Philology'), ('Mathematics'), ('Computer Science'), ('Physics'), ('Chemistry'), ('Pharmacy'), ('Biology'), ('Geosciences'), ('Music'), ('Excellence Cluster'), ('Natural Sciences'), ('Engineering and Technology'), ('Medical and Health Sciences'), ('Agricultural Sciences'), ('Humanities');

INSERT INTO BUCKET:resourcetypes (name,also) VALUES ('Audiovisual',['movingImage','mov','moving image']), ('Book',[]), ('Book Chapter',['chapter','bookPart','bookChapter']), ('Collection',['col','mix','mixed material']), ('Computational Notebook',['computationalNotebook']), ('Conference Paper',['proceedings','conferencePaper']), ('Conference Proceedings',['conferenceProceedings']), ('Data Paper',['dataPaper']), ('Data Set',['dat','dataset']), ('Dissertation',['bachelorThesis','masterThesis','doctoralThesis']), ('Event',[]), ('Image',['stillImage','img','still image','car','cartographic']), ('Instrument',[]), ('Interactive Resource',['interactiveResource','mul','multimedia']), ('Journal',[]);
INSERT INTO BUCKET:resourcetypes (name,also) VALUES ('Journal Article',['article','journalArticle']), ('Model',[]), ('Output Management Plan',['outputManagementPlan']), ('Peer Review',['review','peerReview']), ('Physical Object',['physicalObject','art','artifact','tac','tactile']), ('Poster',['conferenceObject']), ('Preprint',['workingPaper']), ('Report',[]), ('Service',[]), ('Software',[]), ('Sound',['aud','audio']), ('Standard',[]), ('Study Registration',[]), ('Text',['txt','not','notated music','man','manuscript']), ('Workflow',[]), ('Other',['patent','contributionToPeriodical','annotation','lecture','dig','digital','unk','unspecified']);

INSERT INTO BUCKET:languages (name,also) VALUES ('English',['en','eng','Englisch']), ('German',['de','deu','ger','Deutsch']), ('Arabic',['ar','ara','Arabisch']), ('Chinese',['zh','chi','zho','Chinesisch']), ('Danish',['da','dan','Dänisch']), ('Dutch',['nl','nld','dut','Niederländisch']), ('French',['fr','fre','fra','Französisch']), ('Greek',['el','ell','gre','Griechisch']), ('Hebrew',['he','heb','Hebräisch']), ('Hindi',['hi','hin']), ('Italian',['it','ita','Italienisch']), ('Japanese',['ja','jpn','Japanisch']), ('Latin',['la','lat','Latein']), ('Middle Dutch',['dum','Mittelniederländisch']), ('Portuguese',['pt','por','Portugiesisch']), ('Romanian',['ro','rom','rum','Rumänisch']), ('Russian',['ru','rus','Russisch']), ('Serbian',['sr','srp','scc','Serbisch']), ('Slovenien',['sl','slv','Slowenisch']), ('Spanish',['es','spa','Spanisch']), ('Swedish',['sv','swe','Schwedisch']), ('Turkish',['tr','tur','Türkisch']), ('Ukrainian',['uk','ukr','Ukrainisch']);
INSERT INTO BUCKET:languages (name,also) VALUES ('Old Church Slavonic',['chu','cu','Altkirchenslawisch']), ('Czech',['cze','ces','cs','Tschechisch']), ('Old High German',['goh','Althochdeutsch']), ('Ancient Greek',['grc','Altgriechisch']), ('Hungarian',['hun','hu','Ungarisch']), ('Low German',['nds','Plattdeutsch']), ('Old English',['ang','Altenglisch']), ('Polish',['pol','pl','Polnisch']), ('Syriac',['syr','Syrisch']), ('Undetermined',['und','Unbekannt']), ('Not Applicable',['zxx']);

INSERT INTO BUCKET:licenses (name,data) VALUES ('Apache-2.0','https://spdx.org/licenses/Apache-2.0'), ('BSD-2-Clause','https://spdx.org/licenses/BSD-2-Clause'), ('MIT','https://spdx.org/licenses/MIT'), ('ODbL-1.0','https://spdx.org/licenses/ODbL-1.0'), ('zlib-acknowledgement','https://spdx.org/licenses/zlib-acknowledgement');
INSERT INTO BUCKET:licenses (name,data) VALUES ('CC-PDDC','https://spdx.org/licenses/CC-PDDC'), ('CC0-1.0','https://spdx.org/licenses/CC0-1.0'), ('CC-BY-4.0','https://spdx.org/licenses/CC-BY-4.0'), ('CC-BY-3.0','https://spdx.org/licenses/CC-BY-3.0'), ('CC-BY-NC-4.0','https://spdx.org/licenses/CC-BY-NC-4.0'), ('CC-BY-NC-3.0','https://spdx.org/licenses/CC-BY-NC-3.0'), ('CC-BY-ND-4.0','https://spdx.org/licenses/CC-BY-ND-4.0'), ('CC-BY-ND-3.0','https://spdx.org/licenses/CC-BY-ND-3.0'), ('CC-BY-SA-4.0','https://spdx.org/licenses/CC-BY-SA-4.0'), ('CC-BY-SA-3.0','https://spdx.org/licenses/CC-BY-SA-3.0'), ('CC-BY-NC-SA-4.0','https://spdx.org/licenses/CC-BY-NC-SA-4.0'), ('CC-BY-NC-SA-3.0','https://spdx.org/licenses/CC-BY-NC-SA-3.0'), ('CC-BY-NC-ND-4.0','https://spdx.org/licenses/CC-BY-NC-ND-4.0'), ('CC-BY-NC-ND-3.0','https://spdx.org/licenses/CC-BY-NC-ND-3.0');
INSERT INTO BUCKET:licenses (name,data) VALUES ('Public Domain','https://creativecommons.org/publicdomain/mark/1.0/'), ('In Copyright','https://rightsstatements.org/vocab/InC/1.0/');

-- Suggested Properties

INSERT INTO BUCKET:synonyms (name) VALUES ('Subtitle'), ('Abbreviated Title'), ('Short Title'), ('Alternative Title'), ('Translated Title');

INSERT INTO BUCKET:externalitems (name) VALUES ('Website'), ('Documentation'), ('Preprint');

INSERT INTO BUCKET:schemas (name) VALUES ('DataCite'), ('DublinCore'), ('MARC'), ('MODS');
