@startuml backup-endpoint

interface endpoint [
Endpoint
]

node backend [

Backend

]

database database [

Database

]

endpoint <<-->> backend : "  HTTP Server (<b>/api/v1/backup</b>)"
backend -->> database : "  HTTP Client (<b>/command</b>)"

@enduml
