@startuml health-endpoint

interface endpoint [
Endpoint
]

node backend [

Backend

]

database database [

Database

]

endpoint <<-->> backend : " HTTP Server (<b>/health</b>)"
backend -->> backend : " HTTP Client (<b>/version</b>)"
backend -->> database : " HTTP Client (<b>/query</b>)"

@enduml
