@startuml inside

card ctr_db as "CTR: Database" {
    database db as "ArcadeDB"
}

card ctr_be as "CTR: Backend" {
    agent be as "Benthos"
}

circle http as "Endpoints"

card ctr_fe as "CTR: Frontend" #line.dotted; {
    frame fe as "Lowdefy" #line.dotted;
}

database dst as "Backup" #line.dashed;

database src as "Source" #line.dashed;

ctr_db -[dashed]->> dst
ctr_be -[dashed]->> src 
ctr_db <<-- ctr_be
ctr_be -- http
http <<-[dotted]- ctr_fe

@enduml
