@startuml metadata-endpoint

interface endpoint [
Endpoint
]

node backend [

Backend

]

database database [

Database

]

endpoint <<-->> backend : " HTTP Server (<b>/metadata</b>)"
backend -->> database : " HTTP Client (<b>/query</b>)"

@enduml
