@startuml schema-endpoint

interface endpoint [
Endpoint
]

node backend [

Backend

]

database database [

Database

]

endpoint <<-->> backend : " HTTP Server (<b>/schema</b>)"
backend -->> database : " HTTP Client (<b>/query</b>)"
backend -->> backend : " Cache Query"

@enduml
